[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solemon_game = "GwTaRnwmL5qXbmdAqNdcoWeuWFxNLcNiWoNmRFNGhPdL"

[programs.devnet]
solemon_game = "GwTaRnwmL5qXbmdAqNdcoWeuWFxNLcNiWoNmRFNGhPdL"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"